spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
  security:
    user:
      name: lishuo
      password: learnli
server:
  port: 7001
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:7002/eureka/,http://peer3:7003/eureka/
    fetch-registry: true
    register-with-eureka: true
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
  security:
    user:
      name: lishuo
      password: learnli
server:
  port: 7002
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/,http://peer3:7002/eureka/
    fetch-registry: true
    register-with-eureka: true
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3
  security:
    user:
      name: lishuo
      password: learnli
server:
  port: 7003
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/
    fetch-registry: true
    register-with-eureka: true